# Generated by Django 4.2.7 on 2023-11-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameguru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gameguru.user')),
                ('gamesPlayed', models.IntegerField()),
                ('chatHistory', models.TextField()),
            ],
        ),
    ]
