# Generated by Django 4.2.7 on 2023-11-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameguru', '0002_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='gamesWon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='timePlayed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
