# Generated by Django 4.2.7 on 2023-11-18 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameguru', '0005_alter_statistic_username_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='gameType',
            field=models.TextField(default='chess'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='chatHistory',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.TextField()),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
